-- OAuth CSRF state table
-- Stores short-lived state tokens generated by cloud-auth Edge Function.
-- Validated on token exchange to prevent CSRF attacks.
CREATE TABLE IF NOT EXISTS oauth_states (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  state       TEXT NOT NULL UNIQUE,
  provider    TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '10 minutes'),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE oauth_states ENABLE ROW LEVEL SECURITY;

-- Users can only see and delete their own states
CREATE POLICY "Users manage own oauth states"
  ON oauth_states FOR ALL
  USING (auth.uid() = user_id);

-- Index for fast lookup by state token
CREATE INDEX idx_oauth_states_state ON oauth_states (state);

-- Auto-cleanup: pg_cron job or a simple delete-on-expiry handled at app level
-- Edge Function will also clean up expired rows on each validation
